---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kinoite-sway
description: Vanilla Fedora Atomic 44 Kinoite with the official Fedora Sway Spin.

# base-image: quay.io/fedora-ostree-desktops/kinoite
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 44

modules:
  - type: rpm-ostree
    install:
      # Official Fedora Sway branding & configuration defaults
      - sway-config-fedora
      - sway-systemd

      # Core Compositor & Display Utilities
      - sway
      - swaybg
      - swayidle
      - swaylock
      - sddm
      - sddm-wayland-sway
      - sway-config-fedora

      # Official Fedora Sway Stack
      - waybar                 # Status bar
      - foot                   # Default terminal for Fedora Sway
      - fuzzel                 # Application launcher
      - mako                   # Notification daemon
      - xdg-desktop-portal-wlr # Screen sharing / Wayland integration

      # Screenshots, Clipboard & Audio/Brightness Controls - Sway mode
      - grim                   # Screenshot tool
      - slurp                  # Screen region selector
      - wl-clipboard           # Clipboard manager
      - brightnessctl          # Backlight control
      - pamixer                # Audio control CLI
      - playerctl              # Media playback control

      # Local network connectivity from internet
      - tailscale

      # Terminal customization
      - zsh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: files
    files:
      - source: system   # copies `files/system/*` (* means everything inside it) into your image's root folder `/`
        destination: /

  - type: script
    scripts:
      - setup-zsh.sh

  - type: systemd
    system:
      enabled:
        - cross-device-flatpak-sync.timer
        - cross-device-flatpak-update.timer
        - system-healthcheck-monitor-status.timer